In [140]:
#USER INPUT HERE
modweight = 0.5 #change this value

#change the name of the filename being used as the mod_epv for the current matchup
from mod_epv import mod_epv as m_epv

In [141]:
#import statements
import numpy as np
import pandas as pd
#these two imports will always be the same:
from avg_epv import avg_epv as a_epv
from r_conv_pct import conv_pct as r_conv

In [142]:
r_conv = np.matrix(r_conv)

In [143]:
#fn for ceiling division
def ceildiv(a, b):
    return -(-a // b)

#fn for grouping rows into bins of size binsize and taking the average of each bin
def binaverage(matrix, binsize):
    lst = np.array(matrix)
    output = np.zeros((len(lst), (ceildiv(len(lst[0]),binsize))))
    for i in range(0, len(lst)):
        temp = []
        for j in range(0, len(lst[0]), binsize):
            temp2 = lst[i][j:j + binsize]
            temp2 = [x for x in temp2 if x is not None]
            print(len(temp2))
            print(temp2)
            temp.append(sum(temp2) / len(temp2))
        output[i] = np.array(temp)
    return output

In [144]:
#output the average conversion percentage independent of yardline100 bin
print('conversionbydist =', binaverage(r_conv, 10))
#not necessary but cool to look at if we want to use this for something

10
[0.70369999999999999, 0.69638999999999995, 0.71086000000000005, 0.71313000000000004, 0.72533000000000003, 0.73012999999999995, 0.73938000000000004, 0.73450000000000004, 0.75175000000000003, 0.73941999999999997]
10
[0.51983000000000001, 0.60828000000000004, 0.60421999999999998, 0.61275000000000002, 0.61885999999999997, 0.64781999999999995, 0.65337999999999996, 0.65032999999999996, 0.64154, 0.58618999999999999]
10
[0.41503000000000001, 0.53663000000000005, 0.53081999999999996, 0.53581000000000001, 0.54086999999999996, 0.57976000000000005, 0.57886000000000004, 0.57665999999999995, 0.55808999999999997, 0.46945999999999999]
10
[0.36849999999999999, 0.47949999999999998, 0.48298000000000002, 0.47858000000000001, 0.48557, 0.52410999999999996, 0.51619999999999999, 0.51417999999999997, 0.49598999999999999, 0.38657000000000002]
10
[0.35944999999999999, 0.43497999999999998, 0.45301999999999998, 0.43733, 0.44713000000000003, 0.47902, 0.46578999999999998, 0.46356999999999998, 0.44980999999999999,

In [145]:
#place EPVs into 10 yard bins to match conversion percentages
a_epv10 = binaverage(a_epv, 10)
m_epv10 = binaverage(m_epv, 10)

10
[4.974278847698468, 3.037263892372514, 2.9825490902106306, 2.9278342880487473, 2.873119485886864, 2.8184046837249803, 2.7636898815630966, 2.7089750794012133, 2.65426027723933, 2.8485115308013156]
10
[2.7937967286394323, 2.739081926477549, 2.6843671243156653, 2.6296523221537824, 2.574937519991899, 2.520222717830016, 2.465507915668131, 2.4107931135062484, 2.356078311344365, 2.1699579836880534]
10
[2.11524318152617, 2.060528379364287, 2.0058135772024035, 1.9510987750405202, 1.8963839728786365, 1.8416691707167532, 1.7869543685548697, 1.7322395663929864, 1.6775247642311029, 1.6228099620692196]
10
[1.5680951599073363, 1.5133803577454532, 1.4586655555835697, 1.4039507534216864, 1.349235951259803, 1.2945211490979194, 1.2398063469360356, 1.1850915447741526, 1.130376742612269, 1.0756619404503858]
10
[1.0209471382885025, 0.9662323361266192, 0.9115175339647357, 0.8568027318028522, 0.8020879296409689, 0.7473731274790858, 0.6926583253172024, 0.6379435231553187, 0.5832287209934354, 0.5285139188315

In [146]:
#print 10 yard bin averages
np.set_printoptions(precision=3, suppress = True)
print(a_epv10, '\n')
print(m_epv10)

[[ 3.059  2.534  1.869  1.322  0.775  0.228 -0.32  -0.867 -1.414 -1.715]
 [ 2.178  2.081  1.469  0.922  0.375 -0.172 -0.72  -1.267 -1.814 -2.142]
 [ 1.903  1.733  1.201  0.654  0.107 -0.441 -0.988 -1.535 -2.082 -2.438]
 [ 1.679  1.55   1.055  0.508 -0.039 -0.586 -1.134 -1.681 -2.228 -2.611]
 [ 1.492  1.381  0.921  0.373 -0.174 -0.721 -1.268 -1.815 -2.362 -2.773]
 [ 1.385  1.23   0.788  0.241 -0.306 -0.853 -1.401 -1.948 -2.495 -2.933]
 [ 1.338  1.105  0.681  0.134 -0.414 -0.961 -1.508 -2.055 -2.602 -3.067]
 [ 1.259  1.04   0.598  0.05  -0.497 -1.044 -1.591 -2.138 -2.685 -3.178]
 [ 1.252  0.982  0.515 -0.033 -0.58  -1.127 -1.674 -2.221 -2.768 -3.288]] 

[[ 3.705  2.557  1.63   0.711 -0.209 -1.128 -2.047 -2.966 -3.885 -4.391]
 [ 3.783  2.7    1.785  0.866 -0.054 -0.973 -1.892 -2.811 -3.73  -4.282]
 [ 3.812  2.794  1.868  0.949  0.029 -0.89  -1.809 -2.728 -3.647 -4.245]
 [ 3.825  2.863  1.933  1.014  0.095 -0.825 -1.744 -2.663 -3.582 -4.226]
 [ 3.831  2.918  1.989  1.07   0.151 -0.768 -1.6

In [147]:
#create matrix compare fn with multiple use cases
def matrixcompare(m1, m2, operation):
    assert np.matrix(m1).shape == np.matrix(m2).shape, 'matrix size mismatch, cannot compare matrices of different sizes'
    lst1 = np.array(m1)
    lst2 = np.array(m2)
    output = np.zeros((len(lst1), len(lst1[0])))
    for i in range(0, len(lst1)):
        for j in range(0, len(lst1[0])):
            if operation == 'normeddiff':
                #calculate the difference between the mod and the average (how much bigger is the mod epv compared to average?)
                output[i][j] = lst2[i][j] - lst1[i][j]
            elif operation == 'combine':
                output[i][j] = (lst1[i][j] * lst2[i][j]) + lst2[i][j]
            else:
                break
        if operation == 'normeddiff':
            #normalize differences by row (normalized to be a percentage between - modweight and modweight)
            romi = -14 #these two values can be adjusted, but essentially they represent the max differences possible in 2 epvs. 
            romx = 14 #the most 2 epvs can be different is 14 or negative 14, which are the floor and ceiling of m_epv-a_epv
            output[i] = ((2 * (1 + modweight))*((np.array(output[i]) - romi) / (romx - romi)) - (1 + modweight))      
    return output

In [148]:
#compare mod epv with avg epv to create a percent of average epv that represents how much different the modded epv is from the norm
epv_diff = matrixcompare(a_epv10, m_epv10, 'normeddiff') #average EPV *FIRST*. 
print(epv_diff)
#multiply this with our average conversion percentages to modify conversion percentage
m_conv = matrixcompare(epv_diff, r_conv, 'combine')

[[ 0.069  0.002 -0.026 -0.065 -0.105 -0.145 -0.185 -0.225 -0.265 -0.287]
 [ 0.172  0.066  0.034 -0.006 -0.046 -0.086 -0.126 -0.165 -0.205 -0.229]
 [ 0.205  0.114  0.071  0.032 -0.008 -0.048 -0.088 -0.128 -0.168 -0.194]
 [ 0.23   0.141  0.094  0.054  0.014 -0.026 -0.065 -0.105 -0.145 -0.173]
 [ 0.251  0.165  0.115  0.075  0.035 -0.005 -0.045 -0.085 -0.125 -0.155]
 [ 0.263  0.185  0.134  0.094  0.054  0.014 -0.026 -0.066 -0.105 -0.137]
 [ 0.27   0.203  0.15   0.11   0.07   0.03  -0.01  -0.05  -0.09  -0.123]
 [ 0.283  0.213  0.162  0.122  0.083  0.043  0.003 -0.037 -0.077 -0.113]
 [ 0.294  0.223  0.174  0.134  0.095  0.055  0.015 -0.025 -0.065 -0.103]]


In [149]:
r_conv = np.array(r_conv)
r_conv100 = pd.Series(np.repeat([j for i in r_conv for j in i ], 10))
m_conv = np.array(m_conv)
m_conv100 = pd.Series(np.repeat([j for i in m_conv for j in i ], 10))

In [150]:
#insert output statement here
np.savetxt("avg_conv_pct.csv", r_conv100, fmt = '%10.5f')
np.savetxt("mod_conv_pct.csv", m_conv100, fmt = '%10.5f')

In [151]:
#print values for testing purposes:

print('\n raw:\n')
print(r_conv)
print('\n adjusted:\n')
print(m_conv)


 raw:

[[ 0.704  0.696  0.711  0.713  0.725  0.73   0.739  0.735  0.752  0.739]
 [ 0.52   0.608  0.604  0.613  0.619  0.648  0.653  0.65   0.642  0.586]
 [ 0.415  0.537  0.531  0.536  0.541  0.58   0.579  0.577  0.558  0.469]
 [ 0.368  0.479  0.483  0.479  0.486  0.524  0.516  0.514  0.496  0.387]
 [ 0.359  0.435  0.453  0.437  0.447  0.479  0.466  0.464  0.45   0.335]
 [ 0.367  0.401  0.433  0.408  0.42   0.443  0.428  0.426  0.414  0.312]
 [ 0.371  0.376  0.416  0.388  0.398  0.413  0.403  0.401  0.384  0.314]
 [ 0.349  0.358  0.394  0.372  0.375  0.389  0.392  0.39   0.353  0.34 ]
 [ 0.282  0.344  0.358  0.358  0.346  0.367  0.394  0.394  0.316  0.386]]

 adjusted:

[[ 0.752  0.698  0.693  0.666  0.649  0.624  0.603  0.569  0.553  0.527]
 [ 0.609  0.649  0.625  0.609  0.59   0.592  0.571  0.543  0.51   0.452]
 [ 0.5    0.598  0.569  0.553  0.536  0.552  0.528  0.503  0.464  0.379]
 [ 0.453  0.547  0.528  0.505  0.493  0.511  0.482  0.46   0.424  0.32 ]
 [ 0.45   0.507  0.505  0.47 